import os

BOT_TOKEN = os.environ.get("BOT_TOKEN")
ADMIN_IDS = [int(id) for id in os.environ.get("ADMIN_IDS", "").split(",") if id]

SUPABASE_URL = os.environ.get("SUPABASE_URL")
SUPABASE_KEY = os.environ.get("SUPABASE_KEY")

COIN_PER_AD = 10
ADS_PER_DAY = 300
AD_COOLDOWN = 5

DAILY_BONUS = [10, 15, 20, 25, 30, 35, 50]
WEEKLY_BONUS = 100

COINS_PER_POUND = 140
MIN_WITHDRAWAL_COINS = 70000

REFERRAL_BONUS_LEVEL1 = 0.20
REFERRAL_BONUS_LEVEL2 = 0.10
REFERRAL_BONUS_LEVEL3 = 0.05
REFERRAL_MILESTONE_BONUS = 500

WITHDRAWAL_METHODS = {
    "vodafone_cash": "📱 فودافون كاش",
    "paypal": "💳 PayPal",
    "usdt": "₿ USDT (TRC20)"
}
WITHDRAWAL_PROCESSING_TIME = "24-48 ساعة"

CAPTCHA_AFTER_ADS = 50
MAX_REFERRALS_PER_DAY = 20
